export const APP_DEFAULTS = {
  DATE_FORMAT: 'YYYY-MM-DD',
  TIME_FORMAT: 'HH:mm:ss',
  DATETIME_FORMAT: 'YYYY-MM-DD HH:mm:ss',
  ANIMATION_DURATION_MS: 300,
  PAGINATION_LIMIT: 20,
};

export const API_TIMEOUT_MS = 10000;
