export const GEO_CONSTANTS = {
  EARTH_RADIUS_METERS: 6371000,
  EARTH_RADIUS_KM: 6371,
  EARTH_RADIUS_MILES: 3958.8,
  DEFAULT_MAP_ZOOM: 12,
  MAX_ZOOM: 20,
  MIN_ZOOM: 2,
  COORDINATE_PRECISION: 6, // Number of decimal places
  DEFAULT_GEOFENCE_RADIUS_METERS: 500,
};
